/*
 * Wafid Website — Shared Data
 * All services, free zones, blog posts, and content data
 */

// ============ ASSET URLS ============
export const ASSETS = {
  logoLight: "https://d2xsxph8kpxj0f.cloudfront.net/117178986/UbC8QyuJw6HptZEKgwxE7W/logo-wafid_acd15a1b.png",
  logoDark: "https://d2xsxph8kpxj0f.cloudfront.net/117178986/UbC8QyuJw6HptZEKgwxE7W/logo-wafid-reversed_22d7cf42.png",
  heroHome: "https://d2xsxph8kpxj0f.cloudfront.net/117178986/UbC8QyuJw6HptZEKgwxE7W/hero-home-HKeQWrRHtopPag5Ax4doef.webp",
  heroAbout: "https://d2xsxph8kpxj0f.cloudfront.net/117178986/UbC8QyuJw6HptZEKgwxE7W/hero-about-9EntAfF7mWHcb3zrRreCG2.webp",
  heroServices: "https://d2xsxph8kpxj0f.cloudfront.net/117178986/UbC8QyuJw6HptZEKgwxE7W/hero-services-mZzUnaNahUwbtegk8h2n69.webp",
  heroContact: "https://d2xsxph8kpxj0f.cloudfront.net/117178986/UbC8QyuJw6HptZEKgwxE7W/hero-contact-MvQrHnkCa4A3vGv3w9Qgni.webp",
  pattern: "https://d2xsxph8kpxj0f.cloudfront.net/117178986/UbC8QyuJw6HptZEKgwxE7W/geometric-pattern-XpY6Ug56ardXSJTwwArnBP.webp",
};

// ============ SERVICES ============
export interface Service {
  slug: string;
  category: "core" | "supporting" | "specialized" | "premium";
  icon: string; // lucide icon name
  nameEn: string;
  nameAr: string;
  shortEn: string;
  shortAr: string;
  detailEn: string;
  detailAr: string;
}

export const services: Service[] = [
  // CORE SERVICES
  { slug: "mainland-company-formation", category: "core", icon: "Building2", nameEn: "Mainland Company Formation", nameAr: "تأسيس شركة في البر الرئيسي", shortEn: "Establish your mainland LLC or sole establishment in any UAE emirate with full market access.", shortAr: "أسس شركتك في البر الرئيسي في أي إمارة مع وصول كامل للسوق.", detailEn: "A mainland company allows you to trade freely across the UAE and internationally without geographical restrictions. WAFID handles the entire formation process — from initial consultation and trade name reservation to license issuance and establishment card. We guide you through selecting the right legal structure (LLC, Sole Establishment, Civil Company, Branch), choosing business activities, and meeting all regulatory requirements.", detailAr: "تتيح لك شركة البر الرئيسي التداول بحرية في جميع أنحاء الإمارات ودوليًا دون قيود جغرافية. يتولى وافد عملية التأسيس بالكامل — من الاستشارة الأولية وحجز الاسم التجاري إلى إصدار الرخصة وبطاقة المنشأة." },
  { slug: "free-zone-company-formation", category: "core", icon: "Landmark", nameEn: "Free Zone Company Formation", nameAr: "تأسيس شركة في المنطقة الحرة", shortEn: "Set up your business in any UAE free zone with 100% foreign ownership and tax benefits.", shortAr: "أسس عملك في أي منطقة حرة مع ملكية أجنبية 100% ومزايا ضريبية.", detailEn: "UAE free zones offer unique advantages including 100% foreign ownership, full profit repatriation, zero corporate and personal income tax, and streamlined setup processes. WAFID helps you choose the right free zone based on your business activity, budget, visa requirements, and growth plans. We handle the entire registration process across all major free zones.", detailAr: "توفر المناطق الحرة في الإمارات مزايا فريدة تشمل الملكية الأجنبية الكاملة وإعادة الأرباح بالكامل وعدم وجود ضرائب. يساعدك وافد في اختيار المنطقة الحرة المناسبة بناءً على نشاطك التجاري وميزانيتك." },
  { slug: "offshore-company-formation", category: "core", icon: "Globe", nameEn: "Offshore Company Formation", nameAr: "تأسيس شركة خارجية", shortEn: "Register a UAE offshore company for international business, asset protection, and holding structures.", shortAr: "سجل شركة خارجية في الإمارات للأعمال الدولية وحماية الأصول.", detailEn: "A UAE offshore company is ideal for international trading, holding assets, and structuring investments. Offshore entities in jurisdictions like JAFZA and RAK ICC offer privacy, tax efficiency, and international credibility without requiring physical office space in the UAE.", detailAr: "الشركة الخارجية في الإمارات مثالية للتجارة الدولية وحيازة الأصول وهيكلة الاستثمارات. توفر الكيانات الخارجية الخصوصية والكفاءة الضريبية والمصداقية الدولية." },
  { slug: "trade-license", category: "core", icon: "FileCheck", nameEn: "Trade License Issuance", nameAr: "إصدار الرخصة التجارية", shortEn: "Obtain your commercial, professional, or industrial trade license in any UAE jurisdiction.", shortAr: "احصل على رخصتك التجارية أو المهنية أو الصناعية في أي جهة اختصاص.", detailEn: "Every business in the UAE requires a valid trade license to operate legally. WAFID handles the complete licensing process including activity selection, authority approvals, and license issuance for commercial, professional, industrial, and tourism licenses across all emirates.", detailAr: "يتطلب كل عمل تجاري في الإمارات رخصة تجارية سارية. يتولى وافد عملية الترخيص الكاملة بما في ذلك اختيار النشاط والموافقات وإصدار الرخصة." },
  { slug: "trade-license-renewal", category: "core", icon: "RefreshCw", nameEn: "Trade License Renewal", nameAr: "تجديد الرخصة التجارية", shortEn: "Renew your trade license on time with all compliance requirements met.", shortAr: "جدد رخصتك التجارية في الوقت المحدد مع استيفاء جميع متطلبات الامتثال.", detailEn: "Trade licenses in the UAE must be renewed annually. WAFID ensures your renewal is processed on time, with all compliance requirements met including tenancy contracts, approvals, and regulatory clearances.", detailAr: "يجب تجديد الرخص التجارية في الإمارات سنويًا. يضمن وافد معالجة تجديدك في الوقت المحدد مع استيفاء جميع متطلبات الامتثال." },
  { slug: "pro-services", category: "core", icon: "UserCheck", nameEn: "PRO Services", nameAr: "خدمات العلاقات الحكومية", shortEn: "Government liaison and document processing handled by our experienced PRO team.", shortAr: "التعامل مع الجهات الحكومية ومعالجة المستندات بواسطة فريقنا المتمرس.", detailEn: "Our PRO (Public Relations Officer) services cover all government interactions on your behalf. From visa stamping and labor card processing to trade license amendments and ministry approvals — our team handles every government touchpoint so you don't have to.", detailAr: "تغطي خدمات العلاقات الحكومية لدينا جميع التعاملات الحكومية نيابة عنك. من ختم التأشيرات ومعالجة بطاقات العمل إلى تعديلات الرخصة التجارية والموافقات الوزارية." },
  { slug: "visa-residency", category: "core", icon: "CreditCard", nameEn: "Visa & Residency Processing", nameAr: "معالجة التأشيرات والإقامة", shortEn: "Complete visa processing for investors, employees, families, and dependents.", shortAr: "معالجة شاملة للتأشيرات للمستثمرين والموظفين والعائلات.", detailEn: "WAFID processes all types of UAE visas including investor visas, employment visas, family/dependent visas, visit visas, and mission visas. We handle the complete process from entry permit to Emirates ID and medical fitness.", detailAr: "يعالج وافد جميع أنواع تأشيرات الإمارات بما في ذلك تأشيرات المستثمرين والتوظيف والعائلة والزيارة. نتولى العملية الكاملة من تصريح الدخول إلى الهوية الإماراتية." },
  { slug: "emirates-id", category: "core", icon: "Fingerprint", nameEn: "Emirates ID Processing", nameAr: "معالجة الهوية الإماراتية", shortEn: "Fast-track Emirates ID application and renewal for residents and employees.", shortAr: "تسريع طلب وتجديد الهوية الإماراتية للمقيمين والموظفين.", detailEn: "The Emirates ID is mandatory for all UAE residents. WAFID handles the complete application process including biometric appointments, document submission, and card collection.", detailAr: "الهوية الإماراتية إلزامية لجميع المقيمين في الإمارات. يتولى وافد عملية التقديم الكاملة بما في ذلك مواعيد البصمات وتقديم المستندات واستلام البطاقة." },
  { slug: "medical-fitness", category: "core", icon: "HeartPulse", nameEn: "Medical Fitness Coordination", nameAr: "تنسيق الفحص الطبي", shortEn: "Coordinate medical fitness tests required for UAE residency visas.", shortAr: "تنسيق فحوصات اللياقة الطبية المطلوبة لتأشيرات الإقامة.", detailEn: "Medical fitness tests are required for all UAE residency visa applicants. WAFID coordinates appointments at approved medical centers and manages the entire process.", detailAr: "فحوصات اللياقة الطبية مطلوبة لجميع المتقدمين لتأشيرة الإقامة. ينسق وافد المواعيد في المراكز الطبية المعتمدة ويدير العملية بالكامل." },
  // SUPPORTING SERVICES
  { slug: "document-attestation", category: "supporting", icon: "Stamp", nameEn: "Document Attestation & Legalization", nameAr: "تصديق المستندات والتوثيق", shortEn: "Official attestation and legalization of documents for UAE government use.", shortAr: "تصديق وتوثيق رسمي للمستندات للاستخدام الحكومي.", detailEn: "Document attestation is required for many business and personal transactions in the UAE. WAFID handles attestation from embassies, MOFA, notary public, and other authorities for certificates, contracts, and legal documents.", detailAr: "تصديق المستندات مطلوب للعديد من المعاملات التجارية والشخصية في الإمارات. يتولى وافد التصديق من السفارات ووزارة الخارجية والكاتب العدل." },
  { slug: "document-translation", category: "supporting", icon: "Languages", nameEn: "Legal Document Translation", nameAr: "ترجمة المستندات القانونية", shortEn: "Certified Arabic-English translation of legal and business documents.", shortAr: "ترجمة معتمدة عربي-إنجليزي للمستندات القانونية والتجارية.", detailEn: "Many UAE government processes require certified Arabic translations. WAFID provides professional, certified translation services for all business and legal documents.", detailAr: "تتطلب العديد من العمليات الحكومية ترجمات عربية معتمدة. يقدم وافد خدمات ترجمة احترافية ومعتمدة لجميع المستندات التجارية والقانونية." },
  { slug: "bank-account-assistance", category: "supporting", icon: "Wallet", nameEn: "Corporate Bank Account Opening", nameAr: "فتح حساب بنكي للشركات", shortEn: "Assistance opening corporate bank accounts with leading UAE banks.", shortAr: "المساعدة في فتح حسابات بنكية للشركات لدى البنوك الرائدة.", detailEn: "Opening a corporate bank account in the UAE can be challenging. WAFID leverages relationships with major UAE banks to facilitate account opening, prepare documentation, and guide you through compliance requirements.", detailAr: "قد يكون فتح حساب بنكي للشركات في الإمارات تحديًا. يستفيد وافد من علاقاته مع البنوك الكبرى لتسهيل فتح الحساب وإعداد المستندات." },
  { slug: "office-space-ejari", category: "supporting", icon: "Building", nameEn: "Office Space & Ejari Solutions", nameAr: "حلول المكاتب وعقود إيجاري", shortEn: "Find the right office space and manage Ejari registration for your business.", shortAr: "اعثر على المكتب المناسب وأدر تسجيل إيجاري لعملك.", detailEn: "WAFID helps you find the right office solution — from virtual offices and flexi-desks to private offices and warehouses. We also handle Ejari registration, which is mandatory for all commercial leases in Dubai.", detailAr: "يساعدك وافد في إيجاد الحل المكتبي المناسب — من المكاتب الافتراضية إلى المكاتب الخاصة والمستودعات. كما نتولى تسجيل إيجاري الإلزامي." },
  { slug: "business-plan", category: "supporting", icon: "FileText", nameEn: "Business Plan Preparation", nameAr: "إعداد خطة العمل", shortEn: "Professional business plans for licensing, banking, and investor presentations.", shortAr: "خطط عمل احترافية للترخيص والبنوك وعروض المستثمرين.", detailEn: "A well-crafted business plan is essential for license applications, bank account opening, and investor presentations. WAFID prepares comprehensive, professional business plans tailored to UAE requirements.", detailAr: "خطة العمل المتقنة ضرورية لطلبات الترخيص وفتح الحسابات البنكية وعروض المستثمرين. يعد وافد خطط عمل شاملة ومهنية مصممة لمتطلبات الإمارات." },
  { slug: "trademark-registration", category: "supporting", icon: "Shield", nameEn: "Trademark Registration", nameAr: "تسجيل العلامة التجارية", shortEn: "Protect your brand with UAE trademark registration and IP services.", shortAr: "احمِ علامتك التجارية مع خدمات تسجيل العلامات التجارية.", detailEn: "Protect your brand identity in the UAE with trademark registration. WAFID handles the complete process including trademark search, application filing, and registration with the Ministry of Economy.", detailAr: "احمِ هوية علامتك التجارية في الإمارات مع تسجيل العلامة التجارية. يتولى وافد العملية الكاملة بما في ذلك البحث والتقديم والتسجيل لدى وزارة الاقتصاد." },
  // SPECIALIZED SERVICES
  { slug: "golden-visa", category: "specialized", icon: "Award", nameEn: "Golden Visa Processing", nameAr: "معالجة الإقامة الذهبية", shortEn: "Apply for the UAE Golden Visa — 5 or 10-year long-term residency.", shortAr: "تقدم للإقامة الذهبية في الإمارات — إقامة طويلة الأمد 5 أو 10 سنوات.", detailEn: "The UAE Golden Visa offers 5 or 10-year renewable residency for investors, entrepreneurs, specialized talents, researchers, and outstanding students. WAFID guides you through eligibility assessment, document preparation, and the complete application process.", detailAr: "تقدم الإقامة الذهبية إقامة قابلة للتجديد لمدة 5 أو 10 سنوات للمستثمرين ورواد الأعمال والمواهب المتخصصة. يرشدك وافد خلال تقييم الأهلية وإعداد المستندات." },
  { slug: "branch-office-setup", category: "specialized", icon: "GitBranch", nameEn: "Branch / Representative Office Setup", nameAr: "تأسيس فرع أو مكتب تمثيلي", shortEn: "Establish a branch or representative office of your existing company in the UAE.", shortAr: "أسس فرعًا أو مكتبًا تمثيليًا لشركتك الحالية في الإمارات.", detailEn: "If your company is already established outside the UAE, you can open a branch or representative office. WAFID handles the complete setup process including parent company documentation, local approvals, and licensing.", detailAr: "إذا كانت شركتك مؤسسة خارج الإمارات، يمكنك فتح فرع أو مكتب تمثيلي. يتولى وافد عملية التأسيس الكاملة بما في ذلك وثائق الشركة الأم والموافقات المحلية." },
  { slug: "corporate-amendments", category: "specialized", icon: "PenTool", nameEn: "Corporate Amendments", nameAr: "التعديلات المؤسسية", shortEn: "Shareholder changes, activity additions, name changes, and license modifications.", shortAr: "تغييرات المساهمين وإضافة الأنشطة وتغيير الاسم وتعديلات الرخصة.", detailEn: "Business needs evolve. WAFID handles all types of corporate amendments including shareholder transfers, adding or removing business activities, company name changes, manager changes, and capital adjustments.", detailAr: "تتطور احتياجات الأعمال. يتولى وافد جميع أنواع التعديلات المؤسسية بما في ذلك نقل الأسهم وإضافة أو إزالة الأنشطة وتغيير اسم الشركة." },
  { slug: "vat-registration", category: "specialized", icon: "Receipt", nameEn: "VAT Registration & Compliance", nameAr: "تسجيل ضريبة القيمة المضافة والامتثال", shortEn: "Register for VAT and maintain compliance with UAE Federal Tax Authority requirements.", shortAr: "سجل في ضريبة القيمة المضافة وحافظ على الامتثال لمتطلبات الهيئة الاتحادية للضرائب.", detailEn: "VAT registration is mandatory for businesses exceeding AED 375,000 in annual taxable supplies. WAFID handles registration with the Federal Tax Authority, ongoing filing, and compliance management.", detailAr: "تسجيل ضريبة القيمة المضافة إلزامي للشركات التي تتجاوز إيراداتها 375,000 درهم سنويًا. يتولى وافد التسجيل لدى الهيئة الاتحادية للضرائب والتقديم المستمر." },
  { slug: "import-export-code", category: "specialized", icon: "Ship", nameEn: "Import/Export Code Registration", nameAr: "تسجيل رمز الاستيراد والتصدير", shortEn: "Obtain your import/export code for international trade operations.", shortAr: "احصل على رمز الاستيراد والتصدير لعمليات التجارة الدولية.", detailEn: "An import/export code is required for businesses involved in international trade. WAFID handles registration with Dubai Customs and other relevant authorities.", detailAr: "رمز الاستيراد والتصدير مطلوب للشركات المشاركة في التجارة الدولية. يتولى وافد التسجيل لدى جمارك دبي والجهات المعنية." },
  // PREMIUM SERVICES
  { slug: "annual-compliance", category: "premium", icon: "CalendarCheck", nameEn: "Annual Compliance Management", nameAr: "إدارة الامتثال السنوي", shortEn: "Comprehensive annual compliance retainer — never miss a renewal or deadline.", shortAr: "خدمة امتثال سنوية شاملة — لا تفوت أي تجديد أو موعد نهائي.", detailEn: "Our annual compliance retainer ensures your business stays fully compliant year-round. We manage license renewals, visa renewals, establishment card updates, insurance renewals, and all regulatory filings proactively.", detailAr: "تضمن خدمة الامتثال السنوية لدينا بقاء عملك ممتثلاً بالكامل طوال العام. ندير تجديد الرخص والتأشيرات وبطاقات المنشأة والتأمين وجميع الإيداعات التنظيمية." },
  { slug: "company-liquidation", category: "premium", icon: "XCircle", nameEn: "Company Liquidation & Deregistration", nameAr: "تصفية الشركات وإلغاء التسجيل", shortEn: "Professional company closure, liquidation, and deregistration services.", shortAr: "خدمات احترافية لإغلاق الشركات والتصفية وإلغاء التسجيل.", detailEn: "If you need to close your UAE company, WAFID manages the entire liquidation process including cancellation of visas, license cancellation, deregistration, and final compliance clearances.", detailAr: "إذا كنت بحاجة لإغلاق شركتك في الإمارات، يدير وافد عملية التصفية بالكامل بما في ذلك إلغاء التأشيرات والرخصة وإلغاء التسجيل." },
  { slug: "investor-advisory", category: "premium", icon: "TrendingUp", nameEn: "Investor Structuring & Advisory", nameAr: "هيكلة الاستثمار والاستشارات", shortEn: "Strategic advisory on investment structuring, holding companies, and market entry.", shortAr: "استشارات استراتيجية حول هيكلة الاستثمار والشركات القابضة ودخول السوق.", detailEn: "For investors looking to structure their UAE presence optimally, WAFID provides strategic advisory on holding company structures, multi-entity setups, and investment vehicles.", detailAr: "للمستثمرين الذين يتطلعون لهيكلة وجودهم في الإمارات بشكل مثالي، يقدم وافد استشارات استراتيجية حول هياكل الشركات القابضة والكيانات المتعددة." },
  { slug: "multi-entity-setup", category: "premium", icon: "Network", nameEn: "Multi-Entity Setup", nameAr: "تأسيس كيانات متعددة", shortEn: "Set up multiple related entities across different UAE jurisdictions.", shortAr: "أسس كيانات متعددة مترابطة عبر مختلف الولايات القضائية.", detailEn: "Some business structures require entities in multiple jurisdictions — a mainland company for local trading, a free zone entity for international operations, and an offshore company for holding. WAFID designs and implements the optimal multi-entity structure.", detailAr: "تتطلب بعض هياكل الأعمال كيانات في ولايات قضائية متعددة. يصمم وافد وينفذ الهيكل الأمثل متعدد الكيانات." },
];

// ============ FREE ZONES ============
export interface FreeZone {
  name: string;
  slug: string;
  locationEn: string;
  locationAr: string;
  focusEn: string;
  focusAr: string;
  priceFrom: string;
}

export const freeZones: FreeZone[] = [
  { name: "IFZA", slug: "ifza", locationEn: "Dubai", locationAr: "دبي", focusEn: "Multi-sector", focusAr: "متعددة القطاعات", priceFrom: "AED 11,750+" },
  { name: "DMCC", slug: "dmcc", locationEn: "Dubai", locationAr: "دبي", focusEn: "Commodities & Trade", focusAr: "السلع والتجارة", priceFrom: "AED 30,000+" },
  { name: "Meydan Free Zone", slug: "meydan", locationEn: "Dubai", locationAr: "دبي", focusEn: "Multi-sector", focusAr: "متعددة القطاعات", priceFrom: "AED 9,500+" },
  { name: "SHAMS", slug: "shams", locationEn: "Sharjah", locationAr: "الشارقة", focusEn: "Media & Creative", focusAr: "الإعلام والإبداع", priceFrom: "AED 5,750+" },
  { name: "RAKEZ", slug: "rakez", locationEn: "Ras Al Khaimah", locationAr: "رأس الخيمة", focusEn: "Industrial & Trade", focusAr: "الصناعة والتجارة", priceFrom: "AED 7,500+" },
  { name: "DIFC", slug: "difc", locationEn: "Dubai", locationAr: "دبي", focusEn: "Finance & Fintech", focusAr: "المالية والتكنولوجيا المالية", priceFrom: "AED 40,000+" },
  { name: "JAFZA", slug: "jafza", locationEn: "Dubai", locationAr: "دبي", focusEn: "Logistics & Manufacturing", focusAr: "اللوجستيات والتصنيع", priceFrom: "AED 25,000+" },
  { name: "ADGM", slug: "adgm", locationEn: "Abu Dhabi", locationAr: "أبوظبي", focusEn: "Finance & Technology", focusAr: "المالية والتكنولوجيا", priceFrom: "AED 35,000+" },
  { name: "Dubai South", slug: "dubai-south", locationEn: "Dubai", locationAr: "دبي", focusEn: "Aviation & Logistics", focusAr: "الطيران واللوجستيات", priceFrom: "AED 12,000+" },
  { name: "DAFZA", slug: "dafza", locationEn: "Dubai", locationAr: "دبي", focusEn: "Technology & Trade", focusAr: "التكنولوجيا والتجارة", priceFrom: "AED 15,000+" },
  { name: "Dubai Internet City", slug: "dic", locationEn: "Dubai", locationAr: "دبي", focusEn: "Technology & IT", focusAr: "التكنولوجيا وتقنية المعلومات", priceFrom: "AED 20,000+" },
  { name: "Dubai Media City", slug: "dmc", locationEn: "Dubai", locationAr: "دبي", focusEn: "Media & Publishing", focusAr: "الإعلام والنشر", priceFrom: "AED 22,000+" },
  { name: "Dubai Healthcare City", slug: "dhcc", locationEn: "Dubai", locationAr: "دبي", focusEn: "Healthcare & Pharma", focusAr: "الرعاية الصحية والأدوية", priceFrom: "AED 30,000+" },
  { name: "Ajman Free Zone", slug: "afz", locationEn: "Ajman", locationAr: "عجمان", focusEn: "Trading & Services", focusAr: "التجارة والخدمات", priceFrom: "AED 8,000+" },
  { name: "UAQ Free Zone", slug: "uaq", locationEn: "Umm Al Quwain", locationAr: "أم القيوين", focusEn: "General Business", focusAr: "أعمال عامة", priceFrom: "AED 6,500+" },
  { name: "Fujairah Creative City", slug: "fcc", locationEn: "Fujairah", locationAr: "الفجيرة", focusEn: "Media & Education", focusAr: "الإعلام والتعليم", priceFrom: "AED 7,000+" },
  { name: "KIZAD", slug: "kizad", locationEn: "Abu Dhabi", locationAr: "أبوظبي", focusEn: "Industrial & Logistics", focusAr: "الصناعة واللوجستيات", priceFrom: "AED 15,000+" },
  { name: "Masdar City Free Zone", slug: "masdar", locationEn: "Abu Dhabi", locationAr: "أبوظبي", focusEn: "Clean Energy & Sustainability", focusAr: "الطاقة النظيفة والاستدامة", priceFrom: "AED 18,000+" },
  { name: "twofour54", slug: "twofour54", locationEn: "Abu Dhabi", locationAr: "أبوظبي", focusEn: "Media & Entertainment", focusAr: "الإعلام والترفيه", priceFrom: "AED 15,000+" },
  { name: "RAK ICC", slug: "rak-icc", locationEn: "Ras Al Khaimah", locationAr: "رأس الخيمة", focusEn: "Offshore & Holding", focusAr: "الشركات الخارجية والقابضة", priceFrom: "AED 10,000+" },
];

// ============ BLOG POSTS ============
export interface BlogPost {
  id: number;
  slug: string;
  titleEn: string;
  titleAr: string;
  excerptEn: string;
  excerptAr: string;
  categoryEn: string;
  categoryAr: string;
  date: string;
  readTime: string;
}

export const blogPosts: BlogPost[] = [
  { id: 1, slug: "mainland-company-guide", titleEn: "Complete Guide to Mainland Company Setup in the UAE", titleAr: "الدليل الشامل لتأسيس شركة في البر الرئيسي في الإمارات", excerptEn: "Everything you need to know about setting up a mainland company in the UAE.", excerptAr: "كل ما تحتاج معرفته عن تأسيس شركة في البر الرئيسي في الإمارات.", categoryEn: "Company Formation", categoryAr: "تأسيس الشركات", date: "2026-01-15", readTime: "8 min" },
  { id: 2, slug: "free-zone-comparison", titleEn: "Top 10 Free Zones in the UAE: A Comparison Guide", titleAr: "أفضل 10 مناطق حرة في الإمارات: دليل مقارن", excerptEn: "Compare the top free zones to find the best fit for your business.", excerptAr: "قارن بين أفضل المناطق الحرة للعثور على الأنسب لعملك.", categoryEn: "Free Zones", categoryAr: "المناطق الحرة", date: "2026-01-12", readTime: "10 min" },
  { id: 3, slug: "offshore-company-benefits", titleEn: "Benefits of Setting Up an Offshore Company in the UAE", titleAr: "فوائد تأسيس شركة خارجية في الإمارات", excerptEn: "Discover the advantages of UAE offshore companies for international business.", excerptAr: "اكتشف مزايا الشركات الخارجية في الإمارات للأعمال الدولية.", categoryEn: "Company Formation", categoryAr: "تأسيس الشركات", date: "2026-01-10", readTime: "7 min" },
  { id: 4, slug: "dubai-vs-abu-dhabi-business", titleEn: "Dubai vs Abu Dhabi: Where to Set Up Your Business", titleAr: "دبي مقابل أبوظبي: أين تؤسس عملك", excerptEn: "A detailed comparison of Dubai and Abu Dhabi for business setup.", excerptAr: "مقارنة تفصيلية بين دبي وأبوظبي لتأسيس الأعمال.", categoryEn: "Jurisdictions", categoryAr: "الولايات القضائية", date: "2026-01-08", readTime: "9 min" },
  { id: 5, slug: "restaurant-business-guide", titleEn: "How to Start a Restaurant Business in the UAE", titleAr: "كيفية بدء مشروع مطعم في الإمارات", excerptEn: "Complete guide to launching a food and beverage business in the UAE.", excerptAr: "دليل شامل لإطلاق مشروع أغذية ومشروبات في الإمارات.", categoryEn: "Industry Guides", categoryAr: "أدلة القطاعات", date: "2026-01-05", readTime: "8 min" },
  { id: 6, slug: "ecommerce-guide", titleEn: "Starting an E-Commerce Business in the UAE", titleAr: "بدء عمل تجارة إلكترونية في الإمارات", excerptEn: "Complete guide to launching your e-commerce business in the UAE.", excerptAr: "دليل شامل لإطلاق عملك في التجارة الإلكترونية في الإمارات.", categoryEn: "Industry Guides", categoryAr: "أدلة القطاعات", date: "2026-01-03", readTime: "8 min" },
  { id: 7, slug: "consulting-business-guide", titleEn: "How to Start a Consulting Business in the UAE", titleAr: "كيفية بدء عمل استشاري في الإمارات", excerptEn: "Step-by-step guide to setting up a consulting firm in the UAE.", excerptAr: "دليل خطوة بخطوة لتأسيس شركة استشارية في الإمارات.", categoryEn: "Industry Guides", categoryAr: "أدلة القطاعات", date: "2025-12-30", readTime: "7 min" },
  { id: 8, slug: "trading-company-guide", titleEn: "How to Start a Trading Company in the UAE", titleAr: "كيفية بدء شركة تجارية في الإمارات", excerptEn: "Everything about setting up a general trading company in the UAE.", excerptAr: "كل شيء عن تأسيس شركة تجارة عامة في الإمارات.", categoryEn: "Industry Guides", categoryAr: "أدلة القطاعات", date: "2025-12-28", readTime: "8 min" },
  { id: 9, slug: "real-estate-guide", titleEn: "Starting a Real Estate Business in the UAE", titleAr: "بدء عمل عقاري في الإمارات", excerptEn: "How to launch a real estate business in the UAE market.", excerptAr: "كيفية إطلاق عمل عقاري في سوق الإمارات.", categoryEn: "Industry Guides", categoryAr: "أدلة القطاعات", date: "2025-12-25", readTime: "9 min" },
  { id: 10, slug: "tech-startup-guide", titleEn: "Launching a Tech Startup in the UAE", titleAr: "إطلاق شركة تقنية ناشئة في الإمارات", excerptEn: "Guide to starting a technology company in the UAE ecosystem.", excerptAr: "دليل لبدء شركة تكنولوجيا في منظومة الإمارات.", categoryEn: "Industry Guides", categoryAr: "أدلة القطاعات", date: "2025-12-22", readTime: "8 min" },
  { id: 11, slug: "healthcare-business-guide", titleEn: "Starting a Healthcare Business in the UAE", titleAr: "بدء عمل في مجال الرعاية الصحية في الإمارات", excerptEn: "Requirements and process for healthcare businesses in the UAE.", excerptAr: "المتطلبات والعملية لأعمال الرعاية الصحية في الإمارات.", categoryEn: "Industry Guides", categoryAr: "أدلة القطاعات", date: "2025-12-20", readTime: "9 min" },
  { id: 12, slug: "costs-guide", titleEn: "How Much Does It Cost to Start a Business in the UAE?", titleAr: "كم تكلفة تأسيس عمل تجاري في الإمارات؟", excerptEn: "Detailed breakdown of all costs involved in UAE business setup.", excerptAr: "تفصيل شامل لجميع تكاليف تأسيس الأعمال في الإمارات.", categoryEn: "Company Formation", categoryAr: "تأسيس الشركات", date: "2025-12-18", readTime: "10 min" },
  { id: 13, slug: "mainland-vs-freezone", titleEn: "Mainland vs Free Zone: Which Is Right for You?", titleAr: "البر الرئيسي مقابل المنطقة الحرة: أيهما الأنسب لك؟", excerptEn: "A comprehensive comparison to help you choose the right jurisdiction.", excerptAr: "مقارنة شاملة لمساعدتك في اختيار الولاية القضائية المناسبة.", categoryEn: "Jurisdictions", categoryAr: "الولايات القضائية", date: "2025-12-15", readTime: "8 min" },
  { id: 14, slug: "lsa-guide", titleEn: "Understanding the Local Service Agent (LSA) in the UAE", titleAr: "فهم وكيل الخدمات المحلي في الإمارات", excerptEn: "What you need to know about local service agents for mainland companies.", excerptAr: "ما تحتاج معرفته عن وكلاء الخدمات المحلية لشركات البر الرئيسي.", categoryEn: "Company Formation", categoryAr: "تأسيس الشركات", date: "2025-12-12", readTime: "7 min" },
  { id: 15, slug: "dmcc-guide", titleEn: "DMCC Free Zone: Complete Setup Guide", titleAr: "المنطقة الحرة DMCC: دليل التأسيس الشامل", excerptEn: "Everything about setting up in Dubai's premier commodities free zone.", excerptAr: "كل شيء عن التأسيس في المنطقة الحرة الرائدة للسلع في دبي.", categoryEn: "Free Zones", categoryAr: "المناطق الحرة", date: "2025-12-10", readTime: "8 min" },
  { id: 16, slug: "ifza-guide", titleEn: "IFZA Free Zone: Why It's Popular for Startups", titleAr: "المنطقة الحرة IFZA: لماذا تحظى بشعبية لدى الشركات الناشئة", excerptEn: "Discover why IFZA is one of the most popular free zones for new businesses.", excerptAr: "اكتشف لماذا تعد IFZA من أكثر المناطق الحرة شعبية للأعمال الجديدة.", categoryEn: "Free Zones", categoryAr: "المناطق الحرة", date: "2025-12-08", readTime: "7 min" },
  { id: 17, slug: "shams-guide", titleEn: "SHAMS Free Zone: Setup Guide for Creative Businesses", titleAr: "المنطقة الحرة SHAMS: دليل التأسيس للأعمال الإبداعية", excerptEn: "How to set up your creative or media business in SHAMS Sharjah.", excerptAr: "كيفية تأسيس عملك الإبداعي أو الإعلامي في شمس الشارقة.", categoryEn: "Free Zones", categoryAr: "المناطق الحرة", date: "2025-12-05", readTime: "7 min" },
  { id: 18, slug: "rakez-guide", titleEn: "RAKEZ Free Zone: Affordable Business Setup in RAK", titleAr: "المنطقة الحرة RAKEZ: تأسيس أعمال بأسعار معقولة في رأس الخيمة", excerptEn: "Why RAKEZ is the go-to free zone for cost-effective business setup.", excerptAr: "لماذا تعد RAKEZ المنطقة الحرة المفضلة لتأسيس الأعمال بتكلفة فعالة.", categoryEn: "Free Zones", categoryAr: "المناطق الحرة", date: "2025-12-03", readTime: "7 min" },
  { id: 19, slug: "meydan-guide", titleEn: "Meydan Free Zone: A Modern Business Hub", titleAr: "منطقة ميدان الحرة: مركز أعمال حديث", excerptEn: "Explore the benefits of setting up in Meydan Free Zone.", excerptAr: "استكشف فوائد التأسيس في منطقة ميدان الحرة.", categoryEn: "Free Zones", categoryAr: "المناطق الحرة", date: "2025-12-01", readTime: "6 min" },
  { id: 20, slug: "jafza-guide", titleEn: "JAFZA: The UAE's Largest Free Zone for Trade & Logistics", titleAr: "جافزا: أكبر منطقة حرة في الإمارات للتجارة واللوجستيات", excerptEn: "Complete guide to setting up in Jebel Ali Free Zone.", excerptAr: "دليل شامل للتأسيس في المنطقة الحرة بجبل علي.", categoryEn: "Free Zones", categoryAr: "المناطق الحرة", date: "2025-11-28", readTime: "8 min" },
  { id: 21, slug: "difc-vs-adgm", titleEn: "DIFC vs ADGM: Choosing the Right Financial Free Zone", titleAr: "DIFC مقابل ADGM: اختيار المنطقة الحرة المالية المناسبة", excerptEn: "A comparison of the UAE's two premier financial free zones.", excerptAr: "مقارنة بين أبرز منطقتين حرتين ماليتين في الإمارات.", categoryEn: "Free Zones", categoryAr: "المناطق الحرة", date: "2025-11-25", readTime: "9 min" },
  { id: 22, slug: "office-solution-guide", titleEn: "Choosing the Right Office Solution for Your UAE Business", titleAr: "اختيار الحل المكتبي المناسب لعملك في الإمارات", excerptEn: "Virtual offices, co-working, or private offices — which is right for you?", excerptAr: "مكاتب افتراضية أو مشتركة أو خاصة — أيها الأنسب لك؟", categoryEn: "Business Operations", categoryAr: "عمليات الأعمال", date: "2025-11-22", readTime: "7 min" },
  { id: 23, slug: "uae-residence-visa-guide", titleEn: "UAE Residence Visa: Complete Application Guide", titleAr: "تأشيرة الإقامة في الإمارات: دليل التقديم الشامل", excerptEn: "Step-by-step guide to obtaining your UAE residence visa.", excerptAr: "دليل خطوة بخطوة للحصول على تأشيرة الإقامة في الإمارات.", categoryEn: "Visa & Residency", categoryAr: "التأشيرات والإقامة", date: "2025-11-20", readTime: "8 min" },
  { id: 24, slug: "golden-visa-guide", titleEn: "UAE Golden Visa: Eligibility & Application Guide", titleAr: "الإقامة الذهبية في الإمارات: دليل الأهلية والتقديم", excerptEn: "Everything about the UAE Golden Visa program.", excerptAr: "كل شيء عن برنامج الإقامة الذهبية في الإمارات.", categoryEn: "Visa & Residency", categoryAr: "التأشيرات والإقامة", date: "2025-11-18", readTime: "7 min" },
  { id: 25, slug: "bank-account-guide", titleEn: "How to Open a Corporate Bank Account in the UAE", titleAr: "كيفية فتح حساب بنكي للشركات في الإمارات", excerptEn: "Step-by-step guide to opening a business bank account.", excerptAr: "دليل خطوة بخطوة لفتح حساب بنكي تجاري.", categoryEn: "Banking", categoryAr: "الخدمات المصرفية", date: "2025-11-15", readTime: "6 min" },
  { id: 26, slug: "vat-guide", titleEn: "VAT in the UAE: A Complete Guide for Businesses", titleAr: "ضريبة القيمة المضافة في الإمارات: دليل شامل", excerptEn: "Understanding VAT registration, filing, and compliance.", excerptAr: "فهم تسجيل ضريبة القيمة المضافة والتقديم والامتثال.", categoryEn: "Tax & Compliance", categoryAr: "الضرائب والامتثال", date: "2025-11-12", readTime: "9 min" },
  { id: 27, slug: "pro-services-guide", titleEn: "PRO Services in the UAE: What You Need to Know", titleAr: "خدمات العلاقات الحكومية في الإمارات: ما تحتاج معرفته", excerptEn: "Understanding PRO services and why your business needs them.", excerptAr: "فهم خدمات العلاقات الحكومية ولماذا يحتاجها عملك.", categoryEn: "Business Operations", categoryAr: "عمليات الأعمال", date: "2025-11-10", readTime: "7 min" },
  { id: 28, slug: "ip-protection-guide", titleEn: "Protecting Your Intellectual Property in the UAE", titleAr: "حماية الملكية الفكرية في الإمارات", excerptEn: "Guide to trademark, copyright, and patent protection in the UAE.", excerptAr: "دليل حماية العلامات التجارية وحقوق النشر وبراءات الاختراع.", categoryEn: "Legal", categoryAr: "القانونية", date: "2025-11-08", readTime: "8 min" },
  { id: 29, slug: "corporate-tax-guide", titleEn: "UAE Corporate Tax: What Businesses Need to Know", titleAr: "ضريبة الشركات في الإمارات: ما تحتاج الشركات معرفته", excerptEn: "Understanding the UAE's corporate tax framework.", excerptAr: "فهم إطار ضريبة الشركات في الإمارات.", categoryEn: "Tax & Compliance", categoryAr: "الضرائب والامتثال", date: "2025-11-05", readTime: "10 min" },
  { id: 30, slug: "company-liquidation-guide", titleEn: "How to Close a Company in the UAE", titleAr: "كيفية إغلاق شركة في الإمارات", excerptEn: "Complete guide to company liquidation and deregistration.", excerptAr: "دليل شامل لتصفية الشركات وإلغاء التسجيل.", categoryEn: "Company Formation", categoryAr: "تأسيس الشركات", date: "2025-11-03", readTime: "8 min" },
  { id: 31, slug: "top-5-industries", titleEn: "Top 5 Industries for Business in the UAE in 2026", titleAr: "أفضل 5 صناعات للأعمال في الإمارات في 2026", excerptEn: "The most promising sectors for starting a business in the UAE.", excerptAr: "القطاعات الأكثر واعدة لبدء عمل تجاري في الإمارات.", categoryEn: "Industry Guides", categoryAr: "أدلة القطاعات", date: "2025-11-01", readTime: "7 min" },
  { id: 32, slug: "ecommerce-trends", titleEn: "E-Commerce Trends in the UAE: What to Watch", titleAr: "اتجاهات التجارة الإلكترونية في الإمارات", excerptEn: "Key trends shaping the UAE e-commerce landscape.", excerptAr: "الاتجاهات الرئيسية التي تشكل مشهد التجارة الإلكترونية.", categoryEn: "Industry Guides", categoryAr: "أدلة القطاعات", date: "2025-10-28", readTime: "6 min" },
  { id: 33, slug: "csr-guide", titleEn: "Corporate Social Responsibility in the UAE", titleAr: "المسؤولية الاجتماعية للشركات في الإمارات", excerptEn: "How to implement CSR strategies for your UAE business.", excerptAr: "كيفية تنفيذ استراتيجيات المسؤولية الاجتماعية لعملك.", categoryEn: "Business Operations", categoryAr: "عمليات الأعمال", date: "2025-10-25", readTime: "7 min" },
  { id: 34, slug: "future-of-work", titleEn: "The Future of Work in the UAE", titleAr: "مستقبل العمل في الإمارات", excerptEn: "How the UAE is shaping the future of work and business.", excerptAr: "كيف تشكل الإمارات مستقبل العمل والأعمال.", categoryEn: "Thought Leadership", categoryAr: "قيادة الفكر", date: "2025-10-22", readTime: "8 min" },
  { id: 35, slug: "networking-guide", titleEn: "Business Networking in the UAE: A Complete Guide", titleAr: "التواصل التجاري في الإمارات: دليل شامل", excerptEn: "How to build valuable business connections in the UAE.", excerptAr: "كيفية بناء علاقات تجارية قيمة في الإمارات.", categoryEn: "Business Operations", categoryAr: "عمليات الأعمال", date: "2025-10-20", readTime: "6 min" },
  { id: 36, slug: "business-etiquette-guide", titleEn: "UAE Business Etiquette: What Every Entrepreneur Should Know", titleAr: "آداب الأعمال في الإمارات: ما يجب أن يعرفه كل رائد أعمال", excerptEn: "Cultural tips for doing business successfully in the UAE.", excerptAr: "نصائح ثقافية لممارسة الأعمال بنجاح في الإمارات.", categoryEn: "Business Operations", categoryAr: "عمليات الأعمال", date: "2025-10-18", readTime: "7 min" },
  { id: 37, slug: "top-10-challenges", titleEn: "Top 10 Challenges of Starting a Business in the UAE", titleAr: "أهم 10 تحديات لبدء عمل تجاري في الإمارات", excerptEn: "Common challenges and how to overcome them.", excerptAr: "التحديات الشائعة وكيفية التغلب عليها.", categoryEn: "Company Formation", categoryAr: "تأسيس الشركات", date: "2025-10-15", readTime: "8 min" },
  { id: 38, slug: "emirati-culture-guide", titleEn: "Understanding Emirati Culture for Business Success", titleAr: "فهم الثقافة الإماراتية لنجاح الأعمال", excerptEn: "Cultural insights that will help your business thrive in the UAE.", excerptAr: "رؤى ثقافية ستساعد عملك على الازدهار في الإمارات.", categoryEn: "Business Operations", categoryAr: "عمليات الأعمال", date: "2025-10-12", readTime: "7 min" },
  { id: 39, slug: "top-10-reasons-to-invest-in-dubai", titleEn: "Top 10 Reasons to Invest in Dubai", titleAr: "أهم 10 أسباب للاستثمار في دبي", excerptEn: "Why Dubai continues to attract global investors.", excerptAr: "لماذا تستمر دبي في جذب المستثمرين العالميين.", categoryEn: "Thought Leadership", categoryAr: "قيادة الفكر", date: "2025-10-10", readTime: "8 min" },
  { id: 40, slug: "why-uae-is-perfect-for-business", titleEn: "Why the UAE Is Perfect for International Business", titleAr: "لماذا الإمارات مثالية للأعمال الدولية", excerptEn: "The strategic advantages of the UAE for global businesses.", excerptAr: "المزايا الاستراتيجية للإمارات للأعمال العالمية.", categoryEn: "Thought Leadership", categoryAr: "قيادة الفكر", date: "2025-10-08", readTime: "7 min" },
  { id: 41, slug: "business-plan-guide", titleEn: "How to Write a Business Plan for UAE Licensing", titleAr: "كيفية كتابة خطة عمل للترخيص في الإمارات", excerptEn: "A practical guide to creating a business plan that gets approved.", excerptAr: "دليل عملي لإنشاء خطة عمل تحصل على الموافقة.", categoryEn: "Company Formation", categoryAr: "تأسيس الشركات", date: "2025-10-05", readTime: "8 min" },
  { id: 42, slug: "legal-structure-guide", titleEn: "Choosing the Right Legal Structure for Your UAE Business", titleAr: "اختيار الهيكل القانوني المناسب لعملك في الإمارات", excerptEn: "LLC, sole establishment, or branch — which is right for you?", excerptAr: "شركة ذات مسؤولية محدودة أو مؤسسة فردية أو فرع — أيها الأنسب؟", categoryEn: "Company Formation", categoryAr: "تأسيس الشركات", date: "2025-10-03", readTime: "9 min" },
  { id: 43, slug: "trade-license-guide", titleEn: "Types of Trade Licenses in the UAE Explained", titleAr: "أنواع الرخص التجارية في الإمارات", excerptEn: "Understanding commercial, professional, and industrial licenses.", excerptAr: "فهم الرخص التجارية والمهنية والصناعية.", categoryEn: "Company Formation", categoryAr: "تأسيس الشركات", date: "2025-10-01", readTime: "7 min" },
  { id: 44, slug: "freelance-permit-guide", titleEn: "UAE Freelance Permit: Complete Guide for Freelancers", titleAr: "تصريح العمل الحر في الإمارات: دليل شامل", excerptEn: "How to get a freelance permit and work independently in the UAE.", excerptAr: "كيفية الحصول على تصريح عمل حر والعمل بشكل مستقل.", categoryEn: "Company Formation", categoryAr: "تأسيس الشركات", date: "2025-09-28", readTime: "7 min" },
  { id: 45, slug: "trade-license-renewal-guide", titleEn: "Trade License Renewal in the UAE: What You Need to Know", titleAr: "تجديد الرخصة التجارية في الإمارات: ما تحتاج معرفته", excerptEn: "A complete guide to renewing your UAE trade license on time.", excerptAr: "دليل شامل لتجديد رخصتك التجارية في الوقت المحدد.", categoryEn: "Business Operations", categoryAr: "عمليات الأعمال", date: "2025-09-25", readTime: "6 min" },
  { id: 46, slug: "trade-license-amendment-guide", titleEn: "How to Amend Your UAE Trade License", titleAr: "كيفية تعديل رخصتك التجارية في الإمارات", excerptEn: "Guide to adding activities, changing names, and other amendments.", excerptAr: "دليل لإضافة الأنشطة وتغيير الأسماء والتعديلات الأخرى.", categoryEn: "Business Operations", categoryAr: "عمليات الأعمال", date: "2025-09-22", readTime: "6 min" },
  { id: 47, slug: "company-closure-guide", titleEn: "Step-by-Step Guide to Closing a Business in the UAE", titleAr: "دليل خطوة بخطوة لإغلاق عمل تجاري في الإمارات", excerptEn: "Everything you need to know about business closure procedures.", excerptAr: "كل ما تحتاج معرفته عن إجراءات إغلاق الأعمال.", categoryEn: "Company Formation", categoryAr: "تأسيس الشركات", date: "2025-09-20", readTime: "8 min" },
  { id: 48, slug: "top-10-mistakes", titleEn: "Top 10 Mistakes When Setting Up a Business in the UAE", titleAr: "أهم 10 أخطاء عند تأسيس عمل تجاري في الإمارات", excerptEn: "Avoid these common pitfalls when starting your UAE business.", excerptAr: "تجنب هذه الأخطاء الشائعة عند بدء عملك في الإمارات.", categoryEn: "Company Formation", categoryAr: "تأسيس الشركات", date: "2025-09-18", readTime: "8 min" },
  { id: 49, slug: "office-space-guide", titleEn: "Finding the Perfect Office Space in the UAE", titleAr: "إيجاد المكتب المثالي في الإمارات", excerptEn: "Tips for choosing the right office for your business needs.", excerptAr: "نصائح لاختيار المكتب المناسب لاحتياجات عملك.", categoryEn: "Business Operations", categoryAr: "عمليات الأعمال", date: "2025-09-15", readTime: "7 min" },
  { id: 50, slug: "how-wafid-can-help", titleEn: "How Wafid Can Help You Start Your Business in the UAE", titleAr: "كيف يمكن لوافد مساعدتك في بدء عملك في الإمارات", excerptEn: "Discover how Wafid makes business setup simple and stress-free.", excerptAr: "اكتشف كيف يجعل وافد تأسيس الأعمال بسيطًا وخاليًا من التوتر.", categoryEn: "About Wafid", categoryAr: "عن وافد", date: "2025-09-12", readTime: "6 min" },
];

export const blogCategories = [
  { en: "All", ar: "الكل" },
  { en: "Company Formation", ar: "تأسيس الشركات" },
  { en: "Free Zones", ar: "المناطق الحرة" },
  { en: "Jurisdictions", ar: "الولايات القضائية" },
  { en: "Industry Guides", ar: "أدلة القطاعات" },
  { en: "Visa & Residency", ar: "التأشيرات والإقامة" },
  { en: "Tax & Compliance", ar: "الضرائب والامتثال" },
  { en: "Business Operations", ar: "عمليات الأعمال" },
  { en: "Banking", ar: "الخدمات المصرفية" },
  { en: "Legal", ar: "القانونية" },
  { en: "Thought Leadership", ar: "قيادة الفكر" },
  { en: "About Wafid", ar: "عن وافد" },
];

// ============ INDUSTRIES ============
export const industries = [
  { nameEn: "Trading & General Commerce", nameAr: "التجارة العامة", icon: "ShoppingCart" },
  { nameEn: "Technology & IT", nameAr: "التكنولوجيا وتقنية المعلومات", icon: "Cpu" },
  { nameEn: "E-Commerce", nameAr: "التجارة الإلكترونية", icon: "Globe" },
  { nameEn: "Consulting & Professional Services", nameAr: "الاستشارات والخدمات المهنية", icon: "Briefcase" },
  { nameEn: "Real Estate & Construction", nameAr: "العقارات والبناء", icon: "Building2" },
  { nameEn: "Food & Beverage", nameAr: "الأغذية والمشروبات", icon: "UtensilsCrossed" },
  { nameEn: "Healthcare & Wellness", nameAr: "الرعاية الصحية والعافية", icon: "HeartPulse" },
  { nameEn: "Media & Marketing", nameAr: "الإعلام والتسويق", icon: "Megaphone" },
  { nameEn: "Education & Training", nameAr: "التعليم والتدريب", icon: "GraduationCap" },
  { nameEn: "Manufacturing & Industrial", nameAr: "التصنيع والصناعة", icon: "Factory" },
  { nameEn: "Tourism & Hospitality", nameAr: "السياحة والضيافة", icon: "Plane" },
  { nameEn: "Financial Services", nameAr: "الخدمات المالية", icon: "TrendingUp" },
];

// ============ FAQs ============
export const faqs = [
  { qEn: "How long does it take to set up a company in the UAE?", qAr: "كم يستغرق تأسيس شركة في الإمارات؟", aEn: "Depending on the jurisdiction and business type, company setup can take 2-10 business days. Free zone companies are typically the fastest (2-5 days), while mainland companies may take 5-10 days.", aAr: "حسب الولاية القضائية ونوع العمل، يمكن أن يستغرق تأسيس الشركة من 2 إلى 10 أيام عمل. شركات المناطق الحرة عادة الأسرع (2-5 أيام)، بينما شركات البر الرئيسي قد تستغرق 5-10 أيام." },
  { qEn: "Can foreigners own 100% of a company in the UAE?", qAr: "هل يمكن للأجانب امتلاك 100% من شركة في الإمارات؟", aEn: "Yes. Since the 2020 Commercial Companies Law amendment, foreigners can own 100% of mainland companies in most business activities. Free zone companies have always allowed 100% foreign ownership.", aAr: "نعم. منذ تعديل قانون الشركات التجارية في 2020، يمكن للأجانب امتلاك 100% من شركات البر الرئيسي في معظم الأنشطة التجارية. المناطق الحرة سمحت دائمًا بالملكية الأجنبية الكاملة." },
  { qEn: "What is the difference between mainland and free zone?", qAr: "ما الفرق بين البر الرئيسي والمنطقة الحرة؟", aEn: "Mainland companies can trade freely across the UAE and with government entities. Free zone companies operate within their designated zone but offer benefits like 0% corporate tax, 100% profit repatriation, and simplified setup.", aAr: "يمكن لشركات البر الرئيسي التداول بحرية في الإمارات ومع الجهات الحكومية. شركات المناطق الحرة تعمل ضمن منطقتها المحددة لكنها توفر مزايا مثل 0% ضريبة شركات وإعادة الأرباح بالكامل." },
  { qEn: "How much does it cost to start a business in the UAE?", qAr: "كم تكلفة بدء عمل تجاري في الإمارات؟", aEn: "Costs vary significantly by jurisdiction and business type. Free zone packages start from AED 5,750, while mainland setup typically starts from AED 15,000. Use our quote builder for a personalized estimate.", aAr: "تختلف التكاليف بشكل كبير حسب الولاية القضائية ونوع العمل. تبدأ باقات المناطق الحرة من 5,750 درهم، بينما يبدأ تأسيس البر الرئيسي عادة من 15,000 درهم. استخدم أداة عرض الأسعار للحصول على تقدير مخصص." },
  { qEn: "Do I need a physical office to start a business?", qAr: "هل أحتاج مكتبًا فعليًا لبدء عمل تجاري؟", aEn: "Not necessarily. Many free zones offer virtual office or flexi-desk options that satisfy licensing requirements without a dedicated physical space. Mainland companies typically need an Ejari-registered office.", aAr: "ليس بالضرورة. تقدم العديد من المناطق الحرة خيارات مكتب افتراضي أو مكتب مرن تلبي متطلبات الترخيص. شركات البر الرئيسي تحتاج عادة مكتبًا مسجلاً بإيجاري." },
  { qEn: "What is a PRO service?", qAr: "ما هي خدمة العلاقات الحكومية (PRO)؟", aEn: "PRO (Public Relations Officer) services involve handling all government-related paperwork and interactions on behalf of your company — including visa processing, license renewals, document attestation, and ministry approvals.", aAr: "تتضمن خدمات العلاقات الحكومية (PRO) التعامل مع جميع الأوراق والتعاملات الحكومية نيابة عن شركتك — بما في ذلك معالجة التأشيرات وتجديد الرخص وتصديق المستندات والموافقات الوزارية." },
  { qEn: "How do I get a UAE residence visa through my company?", qAr: "كيف أحصل على تأشيرة إقامة في الإمارات من خلال شركتي؟", aEn: "Once your company is licensed, you can sponsor yourself and employees for residence visas. The process involves entry permit, medical fitness test, Emirates ID, and visa stamping. WAFID handles the entire process.", aAr: "بمجرد ترخيص شركتك، يمكنك كفالة نفسك وموظفيك للحصول على تأشيرات إقامة. تتضمن العملية تصريح الدخول والفحص الطبي والهوية الإماراتية وختم التأشيرة. يتولى وافد العملية بالكامل." },
  { qEn: "What is the UAE Golden Visa?", qAr: "ما هي الإقامة الذهبية في الإمارات؟", aEn: "The Golden Visa is a long-term residence visa (5 or 10 years) available to investors, entrepreneurs, specialized talents, researchers, and outstanding students. It does not require a sponsor and allows extended stays outside the UAE.", aAr: "الإقامة الذهبية هي تأشيرة إقامة طويلة الأمد (5 أو 10 سنوات) متاحة للمستثمرين ورواد الأعمال والمواهب المتخصصة والباحثين والطلاب المتميزين. لا تتطلب كفيلاً وتسمح بإقامات ممتدة خارج الإمارات." },
  { qEn: "Is VAT applicable to all businesses in the UAE?", qAr: "هل تنطبق ضريبة القيمة المضافة على جميع الشركات في الإمارات؟", aEn: "VAT registration is mandatory for businesses with annual taxable supplies exceeding AED 375,000. Voluntary registration is available for businesses exceeding AED 187,500. Some supplies are zero-rated or exempt.", aAr: "تسجيل ضريبة القيمة المضافة إلزامي للشركات التي تتجاوز إيراداتها الخاضعة للضريبة 375,000 درهم سنويًا. التسجيل الطوعي متاح للشركات التي تتجاوز 187,500 درهم." },
  { qEn: "Can WAFID help with bank account opening?", qAr: "هل يمكن لوافد المساعدة في فتح حساب بنكي؟", aEn: "Yes. We assist with corporate bank account opening at major UAE banks. We prepare all documentation, coordinate with the bank, and guide you through the compliance process.", aAr: "نعم. نساعد في فتح حسابات بنكية للشركات لدى البنوك الرئيسية في الإمارات. نعد جميع المستندات وننسق مع البنك ونرشدك خلال عملية الامتثال." },
  { qEn: "What documents do I need to start a business in the UAE?", qAr: "ما المستندات التي أحتاجها لبدء عمل تجاري في الإمارات؟", aEn: "Typically you need: passport copies, passport-size photos, proof of address, and a business plan. Additional documents may be required depending on the business activity and jurisdiction.", aAr: "عادة تحتاج: نسخ جواز السفر، صور بحجم جواز السفر، إثبات العنوان، وخطة عمل. قد تكون مستندات إضافية مطلوبة حسب النشاط التجاري والولاية القضائية." },
  { qEn: "How does WAFID's quote builder work?", qAr: "كيف تعمل أداة عرض الأسعار من وافد؟", aEn: "Our quote builder is a simple multi-step form. Answer a few questions about your business needs, and we'll provide a tailored estimate. It takes less than 2 minutes.", aAr: "أداة عرض الأسعار لدينا هي نموذج متعدد الخطوات بسيط. أجب عن بعض الأسئلة حول احتياجات عملك وسنقدم لك تقديرًا مخصصًا. يستغرق أقل من دقيقتين." },
  { qEn: "Does WAFID offer ongoing support after company setup?", qAr: "هل يقدم وافد دعمًا مستمرًا بعد تأسيس الشركة؟", aEn: "Yes. We offer annual compliance management retainers that cover license renewals, visa renewals, and all ongoing government requirements. Your dedicated account manager stays with you.", aAr: "نعم. نقدم خدمات إدارة الامتثال السنوية التي تغطي تجديد الرخص والتأشيرات وجميع المتطلبات الحكومية المستمرة. يبقى مدير حسابك المخصص معك." },
  { qEn: "What is the difference between a trade license and a commercial license?", qAr: "ما الفرق بين الرخصة التجارية والرخصة المهنية؟", aEn: "A commercial license is for trading activities (buying and selling goods), while a professional license is for service-based businesses (consulting, IT services, etc.). Industrial licenses are for manufacturing.", aAr: "الرخصة التجارية للأنشطة التجارية (شراء وبيع البضائع)، بينما الرخصة المهنية للأعمال القائمة على الخدمات (الاستشارات، خدمات تقنية المعلومات، إلخ). الرخص الصناعية للتصنيع." },
  { qEn: "Can I operate my business from home in the UAE?", qAr: "هل يمكنني تشغيل عملي من المنزل في الإمارات؟", aEn: "Some free zones and mainland authorities offer home-based business licenses for specific activities. This is typically available for consulting, freelancing, and e-commerce businesses.", aAr: "تقدم بعض المناطق الحرة وسلطات البر الرئيسي رخص أعمال منزلية لأنشطة محددة. هذا متاح عادة للاستشارات والعمل الحر والتجارة الإلكترونية." },
];
